config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"

  resources :tasks do
    collection do
      get :progress
      get :done
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :employee

  validates_presence_of :name

  def self.assign_task(params)
    employee = Employee.find_by(name: params[:employee_id])
    task = Task.find(params[:id])
    task.update(employee: employee, stimate_days: params[:stimate_days])
  end

  def self.progress_task(params)

    task = Task.find(params[:format])

    if task.employee.name.eql?("sin asignar")
      params
    elsif task.start_task.present?
      params
    elsif task.status.eql?("done")
      params
    else
      time = Time.now + task.stimate_days.to_i.day
      task.update(status: "progress", start_task: time)
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    employee = Employee.find_by(name: "sin asignar")
    @task = Task.create(tasks_params.merge(employee: employee))
    if @task.save
      redirect_to tasks_path
    else
      @errors = @task.errors.full_messages
      render 'new'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    if params[:commit].eql?("Asignar")
      Task.assign_task(tasks_params.merge(id: params[:id]))
      redirect_to tasks_path
    else
      "nada"
    end
  end

  def progress
    Task.progress_task(params)
    redirect_to tasks_path
  end

  def done
    Task.find(params[:format]).update(status: "done")
    redirect_to tasks_path
  end

  def tasks_params
    params.require(:task).permit(:name, :status, :start_task, :employee_id, :stimate_days)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RoRN1
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
  %body
    %main
    .container.fluid
      = yield

app/views/tasks/edit.html.haml
= form_for @task do |f|
  - if @errors
    .error_messages
      %ul
        - @errors.each do |error|
          %li{style: "color:red; font-size:25px;"}= error
          - error
  .form-group.form-group-sm.col-6
    %h1 Asigna un empleado
    %br
    = f.label :assign, 'Asignar a: ', class: "control-label clearfix"
    - names = []
    - Employee.all . each do |emplo|
      - names << emplo.name
    = f.select :employee_id, (names)
    %br
    = f.label :stimate_days, 'Duracion de la tarea', class: "control-label clearfix"
    = f.select :stimate_days, (0..30).to_a
    %br
    = f.submit "Asignar", class: "btn btn-success btn-sm"
    = link_to "Cancelar", tasks_path, class: "btn btn-danger btn-sm"

app/views/tasks/index.html.haml
%h1 Tablero de tareas
= link_to "Crear tarea", new_task_path, class: "btn btn-warning btn-lg"
%table.table.table-bordered
  %thead.thead-dark.text-center
    %tr
      %th Tarea
      %th Estado
      %th Tiempo restante
      %th Asiganda
      %th Asignar
      %th Cambiar estado
  - @tasks.each do |task|
    %tbody
      %tr
        %td= task.name
        %td= task.status
        %td
          - if task.start_task
            - start = task.created_at
            - end_task = task.start_task
            - time = end_task - start
            = Time.at(time).utc.strftime("faltan %e dias")
          - else
            Sin asignar
        %td= task.employee.name
        %td
          = link_to "Asignar", edit_task_path(task), class: "btn btn-info btn-sm"
        %td
          = link_to '<i class="material-icons">restore</i> En progreso'.html_safe, progress_tasks_path(task)
          = link_to '<i class="material-icons">done_all</i> Hecha'.html_safe, done_tasks_path(task)

app/views/tasks/new.html.haml
= form_for @task do |f|
  - if @errors
    .error_messages
      %ul
        - @errors.each do |error|
          %li{style: "color:red; font-size:25px;"}= error
          - error
  .form-group.form-group-sm.col-6
    %h1 Crea una tarea
    %br
    = f.text_field :name, class: "form-control input-lg", placeholder: "Tarea", autocomplete: 'off'
    %br
    = f.submit "Crear Tarea", class: "btn btn-success btn-sm"
    = link_to "Cancelar", tasks_path, class: "btn btn-danger btn-sm"